-- Databricks notebook source
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 100000
     },
     "inputWidgets": {},
     "nuid": "7c2e0890-893a-4c78-be56-1cb98aef6c6f",
     "showTitle": false,
     "tableResultSettingsMap": {
      "0": {
       "dataGridStateBlob": "{\"version\":1,\"tableState\":{\"columnPinning\":{\"left\":[\"#row_number#\"],\"right\":[]},\"columnSizing\":{},\"columnVisibility\":{}},\"settings\":{\"columns\":{}},\"syncTimestamp\":1787848018480}",
       "filterBlob": "{\"version\":1,\"filterGroups\":[{\"enabled\":true,\"filterGroupId\":\"fg_a71d1b48\",\"op\":\"OR\",\"filters\":[{\"filterId\":\"f_25f615bd\",\"enabled\":true,\"columnId\":\"mode_spread\",\"dataType\":\"float\",\"filterType\":\"nulln\"}],\"local\":false,\"updatedAt\":1787847991806},{\"enabled\":true,\"filterGroupId\":\"fg_487c9705\",\"op\":\"OR\",\"filters\":[{\"filterId\":\"f_bbecb58e\",\"enabled\":true,\"columnId\":\"mode_spread\",\"dataType\":\"float\",\"filterType\":\"oneof\"}],\"local\":false,\"updatedAt\":1787848009447}],\"syncTimestamp\":1787848009447}",
       "queryPlanFiltersBlob": "[{\"kind\":\"call\",\"function\":\"and\",\"args\":[{\"kind\":\"call\",\"function\":\"or\",\"args\":[{\"kind\":\"call\",\"function\":\"not\",\"args\":[{\"kind\":\"call\",\"function\":\"in\",\"args\":[{\"kind\":\"identifier\",\"identifier\":\"mode_spread\"},{\"kind\":\"literal\",\"value\":null,\"type\":\"float\"}]}]}]}]}]",
       "tableResultIndex": 0
      }
     },
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- Comprehensive Feature Engineering for College Football Prediction Model\n",
    "-- REFRESHING: Rebuilding with updated score data (10,648 scores populated)\n",
    "-- Target: >57% accuracy predicting home/away winner\n",
    "-- Scheduled to refresh daily\n",
    "\n",
    "CREATE OR REPLACE TABLE workspace.default.cfb_ml_features AS\n",
    "WITH base_games AS (\n",
    "  SELECT *,\n",
    "    CASE WHEN homePoints > awayPoints THEN 1 ELSE 0 END as home_win,\n",
    "    DATEDIFF(startDate, LAG(startDate) OVER (PARTITION BY homeTeam, season ORDER BY startDate)) as home_rest_days,\n",
    "    DATEDIFF(startDate, LAG(startDate) OVER (PARTITION BY awayTeam, season ORDER BY startDate)) as away_rest_days\n",
    "  FROM workspace.default.cfb_merged_data\n",
    "  WHERE homeClassification = 'fbs'\n",
    "    -- Include both completed and future games\n",
    "    -- Post-game features (scores, margins) will be NULL for future games\n",
    "    -- Pre-game features (ELO, spreads, historical stats) will be populated\n",
    "),\n",
    "\n",
    "-- Team performance by location (home/away splits)\n",
    "home_location_stats AS (\n",
    "  SELECT \n",
    "    id,\n",
    "    homeTeam as team,\n",
    "    season,\n",
    "    -- Home points scored, excluding current game (prevents data leakage)\n",
    "    (SUM(homePoints) OVER (PARTITION BY homeTeam, season) - COALESCE(homePoints, 0))\n",
    "      / NULLIF(COUNT(homePoints) OVER (PARTITION BY homeTeam, season) - CASE WHEN homePoints IS NOT NULL THEN 1 ELSE 0 END, 0) as avg_points,\n",
    "    -- Points allowed, excluding current game\n",
    "    (SUM(awayPoints) OVER (PARTITION BY homeTeam, season) - COALESCE(awayPoints, 0))\n",
    "      / NULLIF(COUNT(awayPoints) OVER (PARTITION BY homeTeam, season) - CASE WHEN awayPoints IS NOT NULL THEN 1 ELSE 0 END, 0) as avg_allowed,\n",
    "    -- Win rate, excluding current game\n",
    "    (SUM(CASE WHEN homePoints > awayPoints THEN 1 ELSE 0 END) OVER (PARTITION BY homeTeam, season) - CASE WHEN homePoints > awayPoints THEN 1 ELSE 0 END)\n",
    "      / NULLIF(COUNT(homePoints) OVER (PARTITION BY homeTeam, season) - CASE WHEN homePoints IS NOT NULL THEN 1 ELSE 0 END, 0) as win_rate\n",
    "  FROM base_games\n",
    "),\n",
    "\n",
    "away_location_stats AS (\n",
    "  SELECT \n",
    "    id,\n",
    "    awayTeam as team,\n",
    "    season,\n",
    "    -- Away points scored, excluding current game (prevents data leakage)\n",
    "    (SUM(awayPoints) OVER (PARTITION BY awayTeam, season) - COALESCE(awayPoints, 0))\n",
    "      / NULLIF(COUNT(awayPoints) OVER (PARTITION BY awayTeam, season) - CASE WHEN awayPoints IS NOT NULL THEN 1 ELSE 0 END, 0) as avg_points,\n",
    "    -- Points allowed, excluding current game\n",
    "    (SUM(homePoints) OVER (PARTITION BY awayTeam, season) - COALESCE(homePoints, 0))\n",
    "      / NULLIF(COUNT(homePoints) OVER (PARTITION BY awayTeam, season) - CASE WHEN homePoints IS NOT NULL THEN 1 ELSE 0 END, 0) as avg_allowed,\n",
    "    -- Win rate, excluding current game\n",
    "    (SUM(CASE WHEN awayPoints > homePoints THEN 1 ELSE 0 END) OVER (PARTITION BY awayTeam, season) - CASE WHEN awayPoints > homePoints THEN 1 ELSE 0 END)\n",
    "      / NULLIF(COUNT(awayPoints) OVER (PARTITION BY awayTeam, season) - CASE WHEN awayPoints IS NOT NULL THEN 1 ELSE 0 END, 0) as win_rate\n",
    "  FROM base_games\n",
    "),\n",
    "\n",
    "-- Recent form with rolling windows\n",
    "team_games AS (\n",
    "  SELECT \n",
    "    id,\n",
    "    season,\n",
    "    week,\n",
    "    startDate,\n",
    "    homeTeam as team,\n",
    "    homePoints as points_scored,\n",
    "    awayPoints as points_allowed,\n",
    "    CASE \n",
    "      WHEN homePoints IS NULL OR awayPoints IS NULL THEN NULL\n",
    "      WHEN homePoints > awayPoints THEN 1 \n",
    "      ELSE 0 \n",
    "    END as won,\n",
    "    ABS(homePoints - awayPoints) as margin,\n",
    "    mode_spread as spread,\n",
    "    CASE \n",
    "      WHEN homePoints IS NULL OR awayPoints IS NULL THEN NULL\n",
    "      WHEN mode_spread IS NULL THEN NULL\n",
    "      WHEN (homePoints - awayPoints) > mode_spread THEN 1 \n",
    "      ELSE 0 \n",
    "    END as beat_spread\n",
    "  FROM base_games\n",
    "  \n",
    "  UNION ALL\n",
    "  \n",
    "  SELECT \n",
    "    id,\n",
    "    season,\n",
    "    week,\n",
    "    startDate,\n",
    "    awayTeam as team,\n",
    "    awayPoints as points_scored,\n",
    "    homePoints as points_allowed,\n",
    "    CASE \n",
    "      WHEN homePoints IS NULL OR awayPoints IS NULL THEN NULL\n",
    "      WHEN awayPoints > homePoints THEN 1 \n",
    "      ELSE 0 \n",
    "    END as won,\n",
    "    ABS(awayPoints - homePoints) as margin,\n",
    "    -1 * mode_spread as spread,\n",
    "    CASE \n",
    "      WHEN homePoints IS NULL OR awayPoints IS NULL THEN NULL\n",
    "      WHEN mode_spread IS NULL THEN NULL\n",
    "      WHEN (awayPoints - homePoints) > (-1 * mode_spread) THEN 1 \n",
    "      ELSE 0 \n",
    "    END as beat_spread\n",
    "  FROM base_games\n",
    "),\n",
    "\n",
    "team_rolling AS (\n",
    "  SELECT \n",
    "    team,\n",
    "    season,\n",
    "    week,\n",
    "    startDate,\n",
    "    -- Last 5 games performance (SEASON ONLY - resets each season)\n",
    "    AVG(points_scored) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_points_l5,\n",
    "    AVG(points_allowed) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_allowed_l5,\n",
    "    AVG(margin) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_margin_l5,\n",
    "    AVG(won) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as win_pct_l5,\n",
    "    AVG(beat_spread) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as ats_pct_l5,\n",
    "    \n",
    "    -- Last 5 games performance (CARRYOVER - includes previous season)\n",
    "    AVG(points_scored) OVER (PARTITION BY team ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_points_l5_carryover,\n",
    "    AVG(points_allowed) OVER (PARTITION BY team ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_allowed_l5_carryover,\n",
    "    AVG(margin) OVER (PARTITION BY team ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as avg_margin_l5_carryover,\n",
    "    AVG(won) OVER (PARTITION BY team ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as win_pct_l5_carryover,\n",
    "    AVG(beat_spread) OVER (PARTITION BY team ORDER BY startDate ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING) as ats_pct_l5_carryover,\n",
    "    \n",
    "    -- Last 3 games (recent momentum, SEASON ONLY)\n",
    "    AVG(points_scored) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) as avg_points_l3,\n",
    "    AVG(won) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) as win_pct_l3,\n",
    "    \n",
    "    -- Season-to-date\n",
    "    AVG(points_scored) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as season_avg_points,\n",
    "    AVG(points_allowed) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as season_avg_allowed,\n",
    "    AVG(won) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as season_win_pct,\n",
    "    \n",
    "    -- Current streak\n",
    "    SUM(CASE WHEN won = 1 THEN 1 ELSE 0 END) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING) as wins_l3,\n",
    "    \n",
    "    -- QC: Count unscored games in the L3 momentum window\n",
    "    COUNT(CASE WHEN points_scored IS NULL OR points_allowed IS NULL THEN 1 END)\n",
    "      OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING)\n",
    "      as unscored_games_in_l3_window,\n",
    "    \n",
    "    -- Games played (for filtering)\n",
    "    COUNT(*) OVER (PARTITION BY team, season ORDER BY startDate ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as games_played\n",
    "  FROM team_games\n",
    "),\n",
    "\n",
    "-- Head-to-head history\n",
    "h2h_history AS (\n",
    "  SELECT \n",
    "    bg.id,\n",
    "    COUNT(h2h.id) as h2h_games,\n",
    "    AVG(CASE WHEN h2h.homeTeam = bg.homeTeam AND h2h.homePoints > h2h.awayPoints THEN 1\n",
    "             WHEN h2h.awayTeam = bg.homeTeam AND h2h.awayPoints > h2h.homePoints THEN 1\n",
    "             ELSE 0 END) as home_h2h_win_rate,\n",
    "    AVG(CASE WHEN h2h.homeTeam = bg.homeTeam THEN h2h.homePoints - h2h.awayPoints\n",
    "             ELSE h2h.awayPoints - h2h.homePoints END) as home_h2h_avg_margin\n",
    "  FROM base_games bg\n",
    "  LEFT JOIN base_games h2h ON (\n",
    "    ((h2h.homeTeam = bg.homeTeam AND h2h.awayTeam = bg.awayTeam) OR\n",
    "     (h2h.homeTeam = bg.awayTeam AND h2h.awayTeam = bg.homeTeam))\n",
    "    AND h2h.season < bg.season\n",
    "    AND h2h.season >= bg.season - 3  -- Last 3 seasons\n",
    "  )\n",
    "  GROUP BY bg.id\n",
    "),\n",
    "\n",
    "-- Strength of schedule (CUMULATIVE - no data leakage)\n",
    "-- Running average of opponent strength INCLUDING current opponent's pre-game win%\n",
    "-- Uses CURRENT ROW so current opponent's pre-game strength is included\n",
    "-- This is NOT leakage: season_win_pct already excludes the current game (uses 1 PRECEDING)\n",
    "-- sos_sample_size counts non-NULL opp_win_pct so users can distinguish\n",
    "--   genuine 0.5 from missing data (0 opponents with prior games)\n",
    "sos AS (\n",
    "  SELECT \n",
    "    team,\n",
    "    season,\n",
    "    startDate,\n",
    "    week,\n",
    "    AVG(opp_win_pct) OVER (\n",
    "      PARTITION BY team, season \n",
    "      ORDER BY startDate \n",
    "      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n",
    "    ) as sos_rating,\n",
    "    COUNT(opp_win_pct) OVER (\n",
    "      PARTITION BY team, season \n",
    "      ORDER BY startDate \n",
    "      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n",
    "    ) as sos_sample_size\n",
    "  FROM (\n",
    "    SELECT \n",
    "      bg.homeTeam as team,\n",
    "      bg.season,\n",
    "      bg.startDate,\n",
    "      bg.week,\n",
    "      tr.season_win_pct as opp_win_pct\n",
    "    FROM base_games bg\n",
    "    JOIN team_rolling tr ON tr.team = bg.awayTeam AND tr.season = bg.season AND tr.startDate = bg.startDate\n",
    "    \n",
    "    UNION ALL\n",
    "    \n",
    "    SELECT \n",
    "      bg.awayTeam as team,\n",
    "      bg.season,\n",
    "      bg.startDate,\n",
    "      bg.week,\n",
    "      tr.season_win_pct as opp_win_pct\n",
    "    FROM base_games bg\n",
    "    JOIN team_rolling tr ON tr.team = bg.homeTeam AND tr.season = bg.season AND tr.startDate = bg.startDate\n",
    "  )\n",
    "),\n",
    "\n",
    "-- Spread data quality metadata\n",
    "spread_quality AS (\n",
    "  SELECT \n",
    "    hv.game_id,\n",
    "    hv.std_dev as spread_variance,\n",
    "    CASE \n",
    "      WHEN sc.game_id IS NOT NULL THEN 'VERIFIED'\n",
    "      WHEN hv.std_dev >= 5.0 THEN 'HIGH_VARIANCE'\n",
    "      ELSE 'NORMAL'\n",
    "    END as spread_data_quality\n",
    "  FROM workspace.default.cfb_high_variance_spreads hv\n",
    "  LEFT JOIN workspace.default.cfb_spread_corrections sc ON hv.game_id = sc.game_id\n",
    "  \n",
    "  UNION ALL\n",
    "  \n",
    "  SELECT \n",
    "    sc.game_id,\n",
    "    NULL as spread_variance,\n",
    "    'VERIFIED' as spread_data_quality\n",
    "  FROM workspace.default.cfb_spread_corrections sc\n",
    "  LEFT JOIN workspace.default.cfb_high_variance_spreads hv ON sc.game_id = hv.game_id\n",
    "  WHERE hv.game_id IS NULL  -- Only corrections not already in high variance\n",
    ")\n",
    "\n",
    "-- Final feature set\n",
    "SELECT \n",
    "  bg.id,\n",
    "  bg.season,\n",
    "  bg.week,\n",
    "  bg.homeTeam,\n",
    "  bg.awayTeam,\n",
    "  bg.startDate,\n",
    "  FROM_UTC_TIMESTAMP(TO_TIMESTAMP(bg.startDate), 'America/Chicago') as start_central,\n",
    "  DATE(FROM_UTC_TIMESTAMP(TO_TIMESTAMP(bg.startDate), 'America/Chicago')) as game_date_central,\n",
    "  bg.home_win as target,\n",
    "  \n",
    "  -- Actual game results\n",
    "  bg.homePoints,\n",
    "  bg.awayPoints,\n",
    "  bg.homePoints - bg.awayPoints as actual_margin,\n",
    "  \n",
    "  -- Spread results\n",
    "  (bg.homePoints - bg.awayPoints) - bg.mode_spread as spread_result,\n",
    "  CASE WHEN (bg.homePoints - bg.awayPoints) > bg.mode_spread THEN 1 ELSE 0 END as home_covered_spread,\n",
    "  CASE WHEN (bg.homePoints - bg.awayPoints) = bg.mode_spread THEN 1 ELSE 0 END as push,\n",
    "  CASE \n",
    "    WHEN (bg.homePoints - bg.awayPoints) = bg.mode_spread THEN 'PUSH'\n",
    "    WHEN (bg.homePoints - bg.awayPoints) > bg.mode_spread THEN bg.homeTeam\n",
    "    ELSE bg.awayTeam \n",
    "  END as team_covered,\n",
    "  \n",
    "  -- Game context\n",
    "  CASE WHEN bg.conferenceGame THEN 1 ELSE 0 END as is_conference_game,\n",
    "  CASE WHEN bg.neutralSite THEN 1 ELSE 0 END as is_neutral_site,\n",
    "  COALESCE(bg.attendance, 0) as attendance,\n",
    "  CASE WHEN bg.homeConference = bg.awayConference THEN 1 ELSE 0 END as same_conference,\n",
    "  \n",
    "  -- ELO features (strongest baseline)\n",
    "  bg.homePregameElo,\n",
    "  bg.awayPregameElo,\n",
    "  bg.homePregameElo - bg.awayPregameElo as elo_diff,\n",
    "  \n",
    "  -- Rest advantage\n",
    "  COALESCE(bg.home_rest_days, 7) as home_rest_days,\n",
    "  COALESCE(bg.away_rest_days, 7) as away_rest_days,\n",
    "  COALESCE(bg.home_rest_days, 7) - COALESCE(bg.away_rest_days, 7) as rest_advantage,\n",
    "  \n",
    "  -- Home team recent form (L5)\n",
    "  COALESCE(hr.avg_points_l5, 0) as home_points_l5,\n",
    "  COALESCE(hr.avg_allowed_l5, 0) as home_allowed_l5,\n",
    "  COALESCE(hr.avg_margin_l5, 0) as home_margin_l5,\n",
    "  COALESCE(hr.win_pct_l5, 0) as home_win_pct_l5,\n",
    "  COALESCE(hr.ats_pct_l5, 0) as home_ats_l5,\n",
    "  \n",
    "  -- Away team recent form (L5)\n",
    "  COALESCE(ar.avg_points_l5, 0) as away_points_l5,\n",
    "  COALESCE(ar.avg_allowed_l5, 0) as away_allowed_l5,\n",
    "  COALESCE(ar.avg_margin_l5, 0) as away_margin_l5,\n",
    "  COALESCE(ar.win_pct_l5, 0) as away_win_pct_l5,\n",
    "  COALESCE(ar.ats_pct_l5, 0) as away_ats_l5,\n",
    "  \n",
    "  -- Momentum indicators (L3)\n",
    "  COALESCE(hr.avg_points_l3, 0) as home_points_l3,\n",
    "  COALESCE(hr.win_pct_l3, 0) as home_win_pct_l3,\n",
    "  COALESCE(hr.wins_l3, 0) as home_wins_l3,\n",
    "  COALESCE(ar.avg_points_l3, 0) as away_points_l3,\n",
    "  COALESCE(ar.win_pct_l3, 0) as away_win_pct_l3,\n",
    "  COALESCE(ar.wins_l3, 0) as away_wins_l3,\n",
    "  \n",
    "  -- Season performance\n",
    "  COALESCE(hr.season_avg_points, 0) as home_season_ppg,\n",
    "  COALESCE(hr.season_avg_allowed, 0) as home_season_papg,\n",
    "  COALESCE(hr.season_win_pct, 0) as home_season_win_pct,\n",
    "  COALESCE(ar.season_avg_points, 0) as away_season_ppg,\n",
    "  COALESCE(ar.season_avg_allowed, 0) as away_season_papg,\n",
    "  COALESCE(ar.season_win_pct, 0) as away_season_win_pct,\n",
    "  \n",
    "  -- Home/away splits (historical location performance)\n",
    "  COALESCE(hls.avg_points, 0) as home_at_home_ppg,\n",
    "  COALESCE(hls.win_rate, 0) as home_at_home_win_rate,\n",
    "  COALESCE(als.avg_points, 0) as away_on_road_ppg,\n",
    "  COALESCE(als.win_rate, 0) as away_on_road_win_rate,\n",
    "  \n",
    "  -- Differential features (key predictors - SEASON ONLY)\n",
    "  COALESCE(hr.avg_points_l5, 0) - COALESCE(ar.avg_points_l5, 0) as offense_diff_l5,\n",
    "  COALESCE(ar.avg_allowed_l5, 0) - COALESCE(hr.avg_allowed_l5, 0) as defense_diff_l5,\n",
    "  COALESCE(hr.win_pct_l5, 0) - COALESCE(ar.win_pct_l5, 0) as form_diff_l5,\n",
    "  COALESCE(hr.avg_margin_l5, 0) - COALESCE(ar.avg_margin_l5, 0) as margin_diff_l5,\n",
    "  COALESCE(hr.win_pct_l3, 0) - COALESCE(ar.win_pct_l3, 0) as momentum_diff,\n",
    "  \n",
    "  -- QC: Flag games where momentum window contains unscored (future) games\n",
    "  CASE \n",
    "    WHEN COALESCE(hr.unscored_games_in_l3_window, 0) > 0 OR COALESCE(ar.unscored_games_in_l3_window, 0) > 0 \n",
    "    THEN 'CORRUPTED'\n",
    "    ELSE 'CLEAN'\n",
    "  END as momentum_data_quality,\n",
    "  \n",
    "  -- Carryover features (includes previous season)\n",
    "  COALESCE(hr.ats_pct_l5_carryover, 0) as home_ats_l5_carryover,\n",
    "  COALESCE(ar.ats_pct_l5_carryover, 0) as away_ats_l5_carryover,\n",
    "  COALESCE(hr.win_pct_l5_carryover, 0) - COALESCE(ar.win_pct_l5_carryover, 0) as form_diff_l5_carryover,\n",
    "  COALESCE(hr.avg_margin_l5_carryover, 0) - COALESCE(ar.avg_margin_l5_carryover, 0) as margin_diff_l5_carryover,\n",
    "  \n",
    "  -- Strength of schedule (cumulative, current-season only, no prior-season carryover)\n",
    "  --\n",
    "  -- IMPORTANT: Unlike momentum_diff (which uses a carryover window spanning the prior\n",
    "  -- season via team_rolling's PARTITION BY team ORDER BY startDate pattern), SOS deliberately\n",
    "  -- does NOT carry over between seasons. A team's opponents' win% from last season does\n",
    "  -- not meaningfully describe this season's schedule. The sos CTE partitions by\n",
    "  -- (team, season), so it resets to empty at each season boundary.\n",
    "  --\n",
    "  -- Weeks 1-2 are intentionally blank (sos_diff = 0): teams have 0-1 prior opponents\n",
    "  -- with game data, which is too thin. This is by design, not a bug.\n",
    "  --\n",
    "  -- Week 3 onward: SOS populates with however many current-season opponents have prior\n",
    "  -- game data (sos_sample_size > 0). No minimum-games threshold — a team with only 1-2\n",
    "  -- games played shows SOS based on just those opponents. The sample will be thin early\n",
    "  -- but should not be blank.\n",
    "  CASE WHEN COALESCE(home_sos.sos_sample_size, 0) > 0 AND bg.week > 2 THEN home_sos.sos_rating ELSE 0.5 END as home_sos,\n",
    "  CASE WHEN COALESCE(away_sos.sos_sample_size, 0) > 0 AND bg.week > 2 THEN away_sos.sos_rating ELSE 0.5 END as away_sos,\n",
    "  CASE WHEN COALESCE(home_sos.sos_sample_size, 0) > 0 AND bg.week > 2 THEN home_sos.sos_rating ELSE 0.5 END\n",
    "    - CASE WHEN COALESCE(away_sos.sos_sample_size, 0) > 0 AND bg.week > 2 THEN away_sos.sos_rating ELSE 0.5 END as sos_diff,\n",
    "  COALESCE(home_sos.sos_sample_size, 0) as home_sos_games,\n",
    "  COALESCE(away_sos.sos_sample_size, 0) as away_sos_games,\n",
    "  \n",
    "  -- Head-to-head\n",
    "  COALESCE(h2h.h2h_games, 0) as h2h_games_count,\n",
    "  COALESCE(h2h.home_h2h_win_rate, 0.5) as home_h2h_win_rate,\n",
    "  COALESCE(h2h.home_h2h_avg_margin, 0) as home_h2h_avg_margin,\n",
    "  \n",
    "  -- Market features (Vegas line is highly predictive)\n",
    "  bg.mode_spread,\n",
    "  bg.mode_spread_open,\n",
    "  COALESCE(bg.mode_spread - bg.mode_spread_open, 0) as spread_movement,\n",
    "  CASE WHEN bg.mode_spread < 0 THEN 1 ELSE 0 END as home_favored,\n",
    "  ABS(bg.mode_spread) as spread_magnitude,\n",
    "  \n",
    "  -- Spread data quality (for filtering/weighting)\n",
    "  -- HIGH_VARIANCE: sportsbooks disagreed significantly (std dev ≥5.0)\n",
    "  -- VERIFIED: manually corrected against verified historical odds\n",
    "  -- NORMAL: standard API data quality\n",
    "  COALESCE(sq.spread_variance, 0.0) as spread_variance,\n",
    "  COALESCE(sq.spread_data_quality, 'NORMAL') as spread_data_quality,\n",
    "  \n",
    "  -- Season progression (teams improve/decline over season)\n",
    "  bg.week / 15.0 as season_progress,\n",
    "  CASE WHEN bg.week <= 4 THEN 1 ELSE 0 END as early_season,\n",
    "  CASE WHEN bg.week >= 11 THEN 1 ELSE 0 END as late_season,\n",
    "  \n",
    "  -- Metadata for analysis\n",
    "  hr.games_played as home_games_played,\n",
    "  ar.games_played as away_games_played\n",
    "  \n",
    "FROM base_games bg\n",
    "LEFT JOIN team_rolling hr ON hr.team = bg.homeTeam AND hr.season = bg.season AND hr.startDate = bg.startDate\n",
    "LEFT JOIN team_rolling ar ON ar.team = bg.awayTeam AND ar.season = bg.season AND ar.startDate = bg.startDate\n",
    "LEFT JOIN home_location_stats hls ON hls.id = bg.id\n",
    "LEFT JOIN away_location_stats als ON als.id = bg.id\n",
    "LEFT JOIN sos home_sos ON home_sos.team = bg.homeTeam AND home_sos.season = bg.season AND home_sos.startDate = bg.startDate\n",
    "LEFT JOIN sos away_sos ON away_sos.team = bg.awayTeam AND away_sos.season = bg.season AND away_sos.startDate = bg.startDate\n",
    "LEFT JOIN h2h_history h2h ON h2h.id = bg.id\n",
    "LEFT JOIN spread_quality sq ON sq.game_id = bg.id\n",
    "WHERE (\n",
    "  -- For historical/training data: require 3+ games played\n",
    "  (bg.homePoints IS NOT NULL AND COALESCE(hr.games_played, 0) >= 3 AND COALESCE(ar.games_played, 0) >= 3)\n",
    "  OR\n",
    "  -- For future games: include all with pre-game features\n",
    "  (bg.homePoints IS NULL AND bg.homePregameElo IS NOT NULL)\n",
    ")\n",
    "ORDER BY bg.season, bg.week, bg.startDate"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": false,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": "New Query 2026-08-23 17:54:01.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}